Move Tailwind up to root; rebuild Resume with JSX/Tailwind (#58)
* Move Tailwind config out into top-level of repo

Want to share this config between the Resume stuff and the Next.js stuff; bump it out

* Rewrite with JSX and Tailwind

- Use Tailwind config from shared root of repo
- Most of the structure is back in there
- Typography might not be quite right yet either, but we'll tweak it
- Update minor things in resume.json too; old tools in there idk

Still minor issue with generating the PDF though! This is what to figure out

Might move to `resumed` instead of `resume-cli` ? https://github.com/rbardini/resumed

* Solve compile error

Error was

Failed to compile.
../tailwind/src/config.ts:1:29
Type error: Cannot find module 'tailwindcss' or its corresponding type declarations.

Just stuff a prebuild in there idk

* Bump up typography sizes

- Preset 2 was too small; need to just obey regular body sizes

* Rework dates on Work section

- Don't wrap/break the date ranges 2023-2024 etc
- Keep it aligned with the top of the position title on that line

* Show months next to years

- Show like 9/2024 idk feels fine
- Remove the title that showed the full date
- Use en dash
- Make sure we actually use the correct time zone when we calculate; feeding 2013-06-01 to the formatDate function was returning "May 2013" basically; I'm in ET and I think it uses UTC so it was "Wrong"

* Rework to use `resumed`; Fix PDF generation

- resume-cli is no longer maintained
- PDF generation wasn't working properly with my new theme
- This fixes both

- `resumed`: https://github.com/rbardini/resumed

- Add `generate-pdf` script with some specific line-height overrides and stuff to make the PDF look better
- Use `resumed` commands in NPM scripts; rework `tasks.json` to point at these and use the proper paths
-

* Make "Updated" date use long month name

- Also fix the tasks to depend on the build of the theme when regenerating HTML/PDF; this bit me because I thought it did this

* Fix spacing on mobile

- Felt like we needed a little more space between sections on mobile

* Remove old Pug/SCSS theme; move new theme into its place

- Remove the old @jsonresume-theme-andrewwestling  theme
- Update the name of the @jsonresume-theme-andrewwestling-tw  theme to be jsonresume-theme-andrewwestling
- Update the README of the new theme to be correct
- Fix all the package.json references too, including the installation
- Also make sure @tasks.json is up to date

* Update notes in READMEs

- Tailwind note in next-js
- resumed note in resume