Fix build error
Didn't build before pushing and Vercel threw this error:

```
Type error: Type 'import("/vercel/path0/next-js/app/music/lib/types").PageProps' does not satisfy the constraint 'import("/vercel/path0/next-js/.next/types/app/music/composers/[slug]/page").PageProps'.
  Types of property 'params' are incompatible.
    Type '{ slug: string; }' is missing the following properties from type 'Promise<any>': then, catch, finally, [Symbol.toStringTag]
Static worker exited with code: 1 and signal: null
Error: Command "npm run build" exited with 1
```

The robot fixed it for me