Global Breadcrumbs™; Version bumps; Decluttering and polishing (#56)
* Upgrade to Next.js 15

- Used their recommended codemod thing (https://nextjs.org/docs/app/building-your-application/upgrading/version-15)

`npx @next/codemod@canary upgrade latest`

I decided not to upgrade to React 19 though because it seemed like the react-leaflet thing wasn't yet compatible? idk

* Add Global Breadcrumbs for navigation

App-level:
- Create new `@breadcrumbs` slot and import it into the top-level layout
- Use Next.js Parallel Routes to do it (needed Next.js 15 to make that work)
- Rework the Header to accept the breadcrumbs as a child; now the crumbs live at the top of the page
- Update AWDS page with these changes (show Breadcrumbs there, rework Header example, etc)

Music pages:
- Remove existing Breadcrumbs from Music pages
- Move logic for Music breadcrumbs into `music/lib/breadcrumbs.ts`; import function into `@breadcrumbs/default` for use in generating them
- Fix some vertical margins on Music pages since the Breadcrumbs are removed

Resume:
- Regenerate Resume CSS (and HTML/PDF), because there was a random reset on `span {...}` to make it a block which broke the breadcrumbs (I really gotta rewrite that whole section of the app because it's using Old Tech and annoying to work on)

* Rework `print:hidden` styles

- I can't remember if Tailwind had this built in before but I don't need the print.css anymore; rework

* Use `ExternalLink` component where it makes sense

- Move to top level components folder
- Update imports
- Use on homepage for external links

* Update to React 19 to fix SSR issue with VenueMap

- (Missed this issue in the Next.js 15 upgrade, oops)
- To fix it, it sounds like we need to update react-leaflet to 5; to do that, we need to update react to 19 🦬🪒
- Update react-leaflet to 5.0.0-rc.2 and react 19
- Fix imports
- Remove ssr stuff and dynamic imports; it just works now

* Give the HomeIcon a little border when it's clickable

- Kind of echoing the underline on a link, basically; it's tough to know it's a click target unless you already know; maybe this helps

* Give the Breadcrumbs container a little scrolling

- On small screens, when the breadcrumbs get too long, it was wrapping to the next line (kinda ugly)
- Make the thing scroll horizontally, because you're probably on a phone and can swipe it side to side
- Subtle-ish gradient when the stuff overflows left/right
- I'm not so sure about the `checkScroll` stuff in that useEffect but whatever, it Mostly Works (pretty well honestly) so we'll go with it; we need it so the gradients will show up nicely

* Make the area under the notch on iPhone match the theme

- Saw this on maggieappleton.com, neat
- Notice that it does it on Safari too when you start dragging up/down beyond the bounds of the page

* Knock out the icons

Decluttering

* Fix build error

Didn't build before pushing and Vercel threw this error:

```
Type error: Type 'import("/vercel/path0/next-js/app/music/lib/types").PageProps' does not satisfy the constraint 'import("/vercel/path0/next-js/.next/types/app/music/composers/[slug]/page").PageProps'.
  Types of property 'params' are incompatible.
    Type '{ slug: string; }' is missing the following properties from type 'Promise<any>': then, catch, finally, [Symbol.toStringTag]
Static worker exited with code: 1 and signal: null
Error: Command "npm run build" exited with 1
```

The robot fixed it for me

* Fix build error with VenueMap

Error was

```
Error occurred prerendering page "/music/venues/newmark-theater". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: window is not defined
```

This smelled like the other stuff so I told the robot to fix it and it did

Then I had it refactor the folder structure into a `app/music/components/VenueMap` situation because it had made a wrapper and an inner component; felt right