Fix build error with VenueMap
Error was

```
Error occurred prerendering page "/music/venues/newmark-theater". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: window is not defined
```

This smelled like the other stuff so I told the robot to fix it and it did

Then I had it refactor the folder structure into a `app/music/components/VenueMap` situation because it had made a wrapper and an inner component; felt right